before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
brews:
  - github:
      owner: slimsag
      name: homebrew-update-docker-tags
    folder: Formula
    homepage: https://github.com/slimsag/update-docker-tags
    description: CLI to update Docker tag image versions
    test: |
      system "#{bin}/update-docker-tags --help"
    dependencies:
      - go
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
